# Generated by Django 4.2.16 on 2024-10-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('serie', models.IntegerField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
