# Generated by Django 4.2.16 on 2024-10-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
