# Generated by Django 4.2.16 on 2025-01-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuario', '0002_rename_produtos_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='serie',
            field=models.TextField(max_length=200),
        ),
    ]
